'use strict';
const KEY = 'gymlog_personal_v1';
const uid = () => crypto.randomUUID();
const dateKey = (d = new Date()) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = n => Number(n).toLocaleString(undefined,{maximumFractionDigits:1});
const fmt = d => new Date(d+'T12:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});
const initial = () => ({version:1,routines:[
  {id:'full-body',name:'Full body',focus:'A balanced starting point',exercises:[['Goblet squat',3,10],['Dumbbell bench press',3,10],['Seated cable row',3,12],['Romanian deadlift',3,10]].map(([name,sets,reps])=>({id:uid(),name,sets,reps}))},
  {id:'upper-body',name:'Upper body',focus:'Push & pull',exercises:[['Bench press',3,8],['Lat pulldown',3,10],['Dumbbell shoulder press',3,10],['Cable row',3,12]].map(([name,sets,reps])=>({id:uid(),name,sets,reps}))},
  {id:'lower-body',name:'Lower body',focus:'Legs & posterior chain',exercises:[['Squat',3,8],['Romanian deadlift',3,10],['Leg press',3,12],['Standing calf raise',3,15]].map(([name,sets,reps])=>({id:uid(),name,sets,reps}))}
],sessions:[],weights:[],active:null,selected:'full-body'});
let state,storageError=false;
try{const raw=localStorage.getItem(KEY);state=raw?validate(JSON.parse(raw)):initial();}catch(e){state=initial();storageError=true;}
let page='workout',editingId=null,restEnd=0,toastTimer;
const view=document.getElementById('view');
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){toast('Storage is unavailable or full. Export a backup before leaving.');return false;}}
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4200);}
const totalSets = s => s.exercises.reduce((n,e)=>n+e.sets.filter(x=>x.done).length,0);
const volume = s => s.exercises.reduce((n,e)=>n+e.sets.reduce((v,x)=>v+(x.done?Number(x.weight)*Number(x.reps):0),0),0);
function recentSessions(){const cutoff=new Date();cutoff.setDate(cutoff.getDate()-6);return state.sessions.filter(s=>s.date>=dateKey(cutoff)&&s.date<=dateKey());}
function heading(title,subtitle,action=''){return `<div class="page-heading"><div><p class="eyebrow">YOUR PERSONAL BEST STARTS HERE</p><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`;}
function stats(){return `<div class="stats"><div class="stat"><div class="stat-label">This week <span>◷</span></div><div class="stat-value">${recentSessions().length}<small>sessions</small></div></div><div class="stat"><div class="stat-label">Total workouts <span>◫</span></div><div class="stat-value">${state.sessions.length}<small>logged</small></div></div><div class="stat"><div class="stat-label">Total volume <span>↗</span></div><div class="stat-value">${number(state.sessions.reduce((n,s)=>n+volume(s),0))}<small>kg</small></div></div></div>`;}
function weekCard(){const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const key=dateKey(d);const done=state.sessions.some(s=>s.date===key);return `<div class="day ${done?'done':''} ${i===6?'today':''}"><span>${d.toLocaleDateString(undefined,{weekday:'narrow'})}</span><i aria-label="${fmt(key)}${done?', workout logged':''}">${done?'✓':d.getDate()}</i></div>`;}).join('');return `<div class="card"><div class="section-heading"><h3>Your last 7 days</h3><span class="muted">${recentSessions().length} logged</span></div><div class="week">${days}</div><p class="week-caption">${recentSessions().length?'Every session adds up. Keep showing up.':'A fresh start. Your first session goes here.'}</p></div>`;}
function render(){page=location.hash.slice(1)||'workout';if(!['workout','plans','history','progress'].includes(page))page='workout';document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===page);if(a.dataset.nav===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.getElementById('today').textContent=new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'});view.innerHTML=({workout:workoutView,plans:plansView,history:historyView,progress:progressView}[page])();tick();}
function workoutView(){if(state.active)return activeView();const routine=state.routines.find(r=>r.id===state.selected)||state.routines[0];return heading('Make today count.','Choose a routine. Log your sets. Build your momentum.',`<a class="button secondary" href="#plans">My routines ↗</a>`)+stats()+`<div class="columns"><div><section class="feature"><p class="eyebrow">YOUR NEXT SESSION</p><h2>${esc(routine.name)}</h2><p>${esc(routine.focus||'Your routine, your pace.')}</p><label class="sr-label">Choose routine<select id="routine-select">${state.routines.map(r=>`<option value="${esc(r.id)}" ${r.id===routine.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label><div class="feature-meta"><span>${routine.exercises.length} exercises</span><span>${routine.exercises.reduce((n,e)=>n+e.sets,0)} sets</span><span>Weight in kg</span></div><button class="button lime" data-action="start" data-id="${esc(routine.id)}">Start workout <span>↗</span></button></section><section class="card" style="margin-top:24px"><div class="section-heading"><h3>The lineup</h3><button class="text-button" data-action="edit" data-id="${esc(routine.id)}">Edit routine</button></div>${routine.exercises.map((e,i)=>`<div class="exercise-preview"><span class="number">${String(i+1).padStart(2,'0')}</span><div><strong>${esc(e.name)}</strong><small>${e.sets} sets × ${e.reps} reps</small></div></div>`).join('')}</section></div><div>${weekCard()}<div class="card"><p class="eyebrow">LAST SESSION</p>${state.sessions.length?`<h3>${esc(state.sessions[0].name)}</h3><p class="muted">${fmt(state.sessions[0].date)} · ${totalSets(state.sessions[0])} sets</p><a href="#history" class="text-button">View session history ↗</a>`:`<div class="empty"><div class="empty-symbol">◷</div><h3>Your story starts here.</h3><p>Finish a workout to see your latest session.</p></div>`}</div><p class="note">Use the starter routines as editable templates. Choose weights and targets that suit your experience.</p></div></div>`;}
function activeView(){const s=state.active,done=totalSets(s),total=s.exercises.reduce((n,e)=>n+e.sets.length,0);return heading('One set at a time.',esc(s.name))+`<div class="columns"><section><div class="card"><div class="session-top"><div><h2>${esc(s.name)}</h2><p>${s.exercises.length} exercises · <span id="set-count">${done}</span> / ${total} sets completed</p></div><div class="timer" id="elapsed">00:00</div></div><div class="progress-track" role="progressbar" aria-label="Workout completion" aria-valuenow="${done}" aria-valuemin="0" aria-valuemax="${total}"><div style="width:${done/total*100}%"></div></div><span class="helper">Your session saves as you go.</span></div>${s.exercises.map((e,ei)=>`<section class="card exercise-log"><div class="section-heading"><h3><span class="muted">${String(ei+1).padStart(2,'0')} / </span>${esc(e.name)}</h3></div><div class="set-head"><span>SET</span><span>WEIGHT · KG</span><span>REPS</span><span>DONE</span></div>${e.sets.map((set,si)=>`<div class="set-row"><span class="set-number">${si+1}</span><input aria-label="${esc(e.name)} set ${si+1} weight" data-ex="${ei}" data-set="${si}" data-field="weight" type="number" min="0" max="2000" step="0.5" inputmode="decimal" value="${set.weight}"><input aria-label="${esc(e.name)} set ${si+1} reps" data-ex="${ei}" data-set="${si}" data-field="reps" type="number" min="1" max="1000" step="1" inputmode="numeric" value="${set.reps}"><button class="check-set ${set.done?'checked':''}" aria-label="${esc(e.name)} set ${si+1} complete" aria-pressed="${set.done}" data-action="set" data-ex="${ei}" data-set="${si}">✓</button></div>`).join('')}</section>`).join('')}<label class="session-notes">Session notes<textarea id="notes" maxlength="2000" placeholder="How did it feel? What would you change next time?">${esc(s.notes)}</textarea></label><div class="button-row"><button class="button primary" data-action="finish">Finish workout ✓</button><button class="button secondary" data-action="discard">Discard session</button></div></section><aside><div class="card sticky-card"><p class="eyebrow">TAKE A BREATHER</p><h2>Rest timer</h2><div class="rest-readout" id="rest-timer" aria-live="off">01:30</div><div class="button-row"><button class="button primary" data-action="rest" data-seconds="90">Start 90 sec</button><button class="button secondary" data-action="rest" data-seconds="120">2 min</button><button class="text-button" data-action="stop-rest">Reset</button></div><p class="helper">Start a timer whenever you need a break.</p></div></aside></div>`;}
function plansView(){return heading('Your training, mapped.','Start with a template or build a routine of your own.',`<button class="button primary" data-action="new">+ New routine</button>`)+`<div class="routine-grid">${state.routines.map((r,i)=>`<article class="card routine-card"><span class="tag">ROUTINE ${String(i+1).padStart(2,'0')}</span><h2>${esc(r.name)}</h2><p class="muted">${esc(r.focus||'Custom routine')}</p><ul>${r.exercises.map(e=>`<li>${esc(e.name)} <strong>· ${e.sets} × ${e.reps}</strong></li>`).join('')}</ul><div class="button-row"><button class="button primary" data-action="start" data-id="${esc(r.id)}">${state.active?'Resume workout':'Start workout'} ↗</button><button class="button secondary" data-action="edit" data-id="${esc(r.id)}">Edit</button><button class="text-button" data-action="delete-routine" data-id="${esc(r.id)}" aria-label="Delete ${esc(r.name)} routine">Delete</button></div></article>`).join('')}</div>`;}
function historyView(){return heading('Every rep has a record.','Your completed sessions, all in one place.')+stats()+(state.sessions.length?state.sessions.map(s=>`<details class="card history-card"><summary><div><h3>${esc(s.name)}</h3><p>${fmt(s.date)} · ${Math.max(1,Math.round(s.duration/60000))} min · ${totalSets(s)} sets</p></div><span class="badge">${number(volume(s))} kg volume ＋</span></summary><div class="details">${s.exercises.filter(e=>e.sets.some(x=>x.done)).map(e=>`<div class="detail-row"><strong>${esc(e.name)}</strong><span>${e.sets.filter(x=>x.done).map(x=>`${number(x.weight)} kg × ${x.reps}`).join(' / ')}</span></div>`).join('')}${s.notes?`<p class="note">${esc(s.notes)}</p>`:''}</div></details>`).join(''):`<div class="card empty"><div class="empty-symbol">◷</div><h2>A blank page. A fresh start.</h2><p>Once you finish a workout, the sets, weights, and notes will appear here.</p><a class="button primary" href="#workout">Log your first workout ↗</a></div>`);}
function progressView(){const records=new Map();state.sessions.forEach(s=>s.exercises.forEach(e=>e.sets.filter(x=>x.done).forEach(x=>{const key=e.name.trim().toLowerCase();if(!records.has(key)||records.get(key).weight<Number(x.weight))records.set(key,{name:e.name,weight:Number(x.weight)});})));const weights=[...state.weights].sort((a,b)=>a.date.localeCompare(b.date));return heading('See how far you’ve come.','Small improvements. A bigger picture.')+stats()+`<div class="columns"><div class="card"><div class="section-heading"><h2>Body weight</h2><span class="badge">${weights.length?number(weights.at(-1).value)+' kg':'No entries yet'}</span></div>${weightChart(weights)}<form id="weight-form" class="weight-form"><label>Date<input type="date" name="date" value="${dateKey()}" max="${dateKey()}" required></label><label>Weight · kg<input type="number" name="weight" placeholder="e.g. 72.5" min="20" max="500" step="0.1" required></label><button class="button primary">Add entry</button></form><div class="weight-list">${weights.slice(-6).reverse().map(w=>`<div class="weight-item"><span>${fmt(w.date)}</span><strong>${number(w.value)} kg</strong></div>`).join('')}</div><p class="helper">Adding the same date updates that entry.</p></div><div class="card"><h2>Personal records</h2><p class="muted">Heaviest completed set for each exercise.</p>${records.size?[...records.values()].sort((a,b)=>b.weight-a.weight).map(r=>`<div class="record"><span>${esc(r.name)}</span><strong>${number(r.weight)} kg ↗</strong></div>`).join(''):`<div class="empty"><div class="empty-symbol">↗</div><p>Log a completed set to start building your records.</p></div>`}</div></div><div class="mobile-backup"><button class="text-button" data-action="export">Export backup ↗</button><button class="text-button" data-action="import">Restore backup</button><p class="helper">Records stay in this browser. Export a backup before changing devices.</p></div>`;}
function weightChart(weights){if(weights.length<2)return `<div class="empty"><div class="empty-symbol">↗</div><p>${weights.length?'Add one more entry to see your trend.':'Log your weight to see your trend over time.'}</p></div>`;const values=weights.map(w=>w.value),low=Math.min(...values)-1,high=Math.max(...values)+1;const start=new Date(weights[0].date+'T12:00:00').getTime(),end=new Date(weights.at(-1).date+'T12:00:00').getTime();const points=weights.map(w=>`${12+(new Date(w.date+'T12:00:00').getTime()-start)/(end-start)*476},${140-(w.value-low)/(high-low)*120}`).join(' ');return `<svg class="chart" viewBox="0 0 500 160" role="img" aria-label="Weight trend from ${esc(weights[0].value)} to ${esc(weights.at(-1).value)} kilograms"><path d="M12 40H488 M12 90H488 M12 140H488" stroke="#e2e8de" fill="none"/><polyline points="${points}" stroke="#426a36" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/>${points.split(' ').map(p=>{const[x,y]=p.split(',');return `<circle cx="${x}" cy="${y}" r="4" fill="#d6ff63" stroke="#426a36" stroke-width="2"/>`;}).join('')}</svg><div class="chart-labels"><span>${fmt(weights[0].date)}</span><span>${fmt(weights.at(-1).date)}</span></div>`;}
function start(id){if(state.active){location.hash='workout';render();toast('Your current workout is ready to continue.');return;}const r=state.routines.find(r=>r.id===id);if(!r)return;state.selected=id;state.active={id:uid(),routineId:r.id,name:r.name,date:dateKey(),startedAt:Date.now(),notes:'',exercises:r.exercises.map(e=>{const previous=state.sessions.flatMap(s=>s.exercises).find(x=>x.name.toLowerCase()===e.name.toLowerCase());return {id:e.id,name:e.name,sets:Array.from({length:e.sets},(_,i)=>({weight:previous?.sets[i]?.weight||0,reps:e.reps,done:false}))};})};save();location.hash='workout';render();window.scrollTo({top:0});}
function ask(title,text,label,callback){const d=document.getElementById('confirm-dialog');document.getElementById('confirm-title').textContent=title;document.getElementById('confirm-text').textContent=text;document.getElementById('confirm-action').textContent=label;d.returnValue='';d.onclose=()=>{if(d.returnValue==='confirm')callback();};d.showModal();}
function finish(){const s=state.active;if(!totalSets(s)){toast('Complete at least one set before finishing.');return;}if(!s.exercises.every(e=>e.sets.every(x=>Number.isFinite(Number(x.weight))&&x.weight>=0&&x.weight<=2000&&Number.isInteger(Number(x.reps))&&x.reps>=1&&x.reps<=1000))){toast('Check your weights and reps before finishing.');return;}ask('Finish this workout?',`${totalSets(s)} completed sets will be added to your history. Incomplete sets will not count toward your records.`,'Save workout',()=>{state.sessions.unshift({...state.active,duration:Date.now()-state.active.startedAt});state.active=null;restEnd=0;save();location.hash='history';render();toast('Workout saved. Another session in the books.');});}
function edit(id){editingId=id||null;const r=state.routines.find(r=>r.id===id);const form=document.getElementById('routine-form');form.reset();form.elements.name.value=r?.name||'';form.elements.focus.value=r?.focus||'';document.getElementById('editor-title').textContent=r?'Edit routine':'New routine';document.getElementById('exercise-fields').innerHTML='';(r?.exercises||[{name:'',sets:3,reps:10}]).forEach(addExercise);document.getElementById('editor').showModal();}
function addExercise(e={name:'',sets:3,reps:10}){const row=document.createElement('div');row.className='editor-exercise';row.dataset.id=e.id||uid();row.innerHTML=`<label>Exercise<input class="exercise-name" value="${esc(e.name)}" maxlength="80" required placeholder="Exercise name"></label><label>Sets<input class="exercise-sets" type="number" value="${e.sets}" min="1" max="20" required></label><label>Reps<input class="exercise-reps" type="number" value="${e.reps}" min="1" max="1000" required></label><button type="button" class="icon-button" aria-label="Remove exercise">×</button>`;row.querySelector('button').onclick=()=>{if(document.querySelectorAll('.editor-exercise').length===1){toast('Keep at least one exercise.');return;}row.remove();};document.getElementById('exercise-fields').append(row);}
document.getElementById('routine-form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;const name=form.elements.name.value.trim();if(!name){toast('Enter a routine name.');return;}const exercises=[...document.querySelectorAll('.editor-exercise')].map(row=>({id:row.dataset.id,name:row.querySelector('.exercise-name').value.trim(),sets:Number(row.querySelector('.exercise-sets').value),reps:Number(row.querySelector('.exercise-reps').value)}));if(exercises.some(x=>!x.name)){toast('Give every exercise a name.');return;}const r={id:editingId||uid(),name,focus:form.elements.focus.value.trim(),exercises};if(editingId)state.routines=state.routines.map(old=>old.id===editingId?r:old);else state.routines.push(r);save();document.getElementById('editor').close();render();toast('Routine saved.');};
document.getElementById('add-exercise').onclick=()=>{if(document.querySelectorAll('.editor-exercise').length>=30){toast('A routine can have up to 30 exercises.');return;}addExercise();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById('editor').close());
view.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;if(action==='start')start(b.dataset.id);if(action==='new')edit();if(action==='edit')edit(b.dataset.id);if(action==='finish')finish();if(action==='discard')ask('Discard current workout?','Completed sessions are kept. The current unsaved workout will be removed.','Discard workout',()=>{state.active=null;restEnd=0;save();render();});if(action==='delete-routine'){if(state.routines.length===1){toast('Keep at least one routine.');return;}ask('Delete this routine?','Your completed sessions will remain in history.','Delete routine',()=>{state.routines=state.routines.filter(r=>r.id!==b.dataset.id);save();render();});}if(action==='set'){const set=state.active.exercises[Number(b.dataset.ex)].sets[Number(b.dataset.set)];if(!Number.isFinite(Number(set.weight))||set.weight<0||set.weight>2000||!Number.isInteger(Number(set.reps))||set.reps<1||set.reps>1000){toast('Enter a valid weight and a whole number of reps.');return;}set.done=!set.done;save();render();}if(action==='rest'){restEnd=Date.now()+Number(b.dataset.seconds)*1000;tick();}if(action==='stop-rest'){restEnd=0;tick();}if(action==='export')exportBackup();if(action==='import')document.getElementById('import').click();});
view.addEventListener('change',e=>{if(e.target.id==='routine-select'){state.selected=e.target.value;save();render();}});
view.addEventListener('input',e=>{const t=e.target;if(t.dataset.field&&state.active){const set=state.active.exercises[Number(t.dataset.ex)].sets[Number(t.dataset.set)];if(t.value!==''&&!t.checkValidity()){toast('Use a valid weight or a whole number of reps.');t.value=set[t.dataset.field];return;}set[t.dataset.field]=t.value===''?'':Number(t.value);save();}if(t.id==='notes'&&state.active){state.active.notes=t.value;save();}});
view.addEventListener('submit',e=>{if(e.target.id!=='weight-form')return;e.preventDefault();const f=e.target,w={date:f.elements.date.value,value:Number(f.elements.weight.value)};if(w.date>dateKey()||!validDate(w.date)||!Number.isFinite(w.value)||w.value<20||w.value>500){toast('Enter a valid date and weight.');return;}state.weights=state.weights.filter(x=>x.date!==w.date);state.weights.push(w);save();render();toast('Weight recorded.');});
function tick(){const elapsed=document.getElementById('elapsed');if(elapsed&&state.active){const sec=Math.max(0,Math.floor((Date.now()-state.active.startedAt)/1000));elapsed.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}const rest=document.getElementById('rest-timer');if(rest){const seconds=restEnd?Math.max(0,Math.ceil((restEnd-Date.now())/1000)):90;rest.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}if(restEnd&&Date.now()>=restEnd){restEnd=0;toast('Rest timer finished. Ready for your next set?');}}
function exportBackup(){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`gymlog-personal-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup downloaded. Keep it somewhere safe.');}
function validDate(d){return typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(new Date(d+'T12:00:00').getTime())&&dateKey(new Date(d+'T12:00:00'))===d;}
function validate(data){const str=(v,max=2000)=>typeof v==='string'&&v.length<=max;const num=(v,min,max)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;const assert=x=>{if(!x)throw Error('Invalid GymLog Personal backup');};assert(data&&data.version===1&&Array.isArray(data.routines)&&data.routines.length>0&&data.routines.length<=500&&Array.isArray(data.sessions)&&data.sessions.length<=10000&&Array.isArray(data.weights)&&data.weights.length<=10000);const ids=new Set();data.routines.forEach(r=>{assert(r&&str(r.id,100)&&!ids.has(r.id)&&str(r.name,70)&&r.name.trim()&&str(r.focus,120)&&Array.isArray(r.exercises)&&r.exercises.length>0&&r.exercises.length<=30);ids.add(r.id);r.exercises.forEach(e=>assert(e&&str(e.id,100)&&str(e.name,80)&&e.name.trim()&&Number.isInteger(e.sets)&&num(e.sets,1,20)&&Number.isInteger(e.reps)&&num(e.reps,1,1000)));});const session=(s,active=false)=>{assert(s&&str(s.id,100)&&str(s.name,70)&&validDate(s.date)&&num(s.startedAt,0,1e15)&&str(s.notes)&&Array.isArray(s.exercises)&&s.exercises.length>0&&s.exercises.length<=30);if(!active)assert(num(s.duration,0,1e15));s.exercises.forEach(e=>{assert(e&&str(e.id,100)&&str(e.name,80)&&Array.isArray(e.sets)&&e.sets.length>0&&e.sets.length<=20);e.sets.forEach(x=>assert(x&&((active&&x.weight==='')||num(x.weight,0,2000))&&((active&&x.reps==='')||(num(x.reps,1,1000)&&Number.isInteger(x.reps)))&&typeof x.done==='boolean'));});};data.sessions.forEach(s=>session(s));if(data.active)session(data.active,true);data.weights.forEach(w=>assert(w&&validDate(w.date)&&num(w.value,20,500)));return {version:1,routines:data.routines,sessions:data.sessions,weights:data.weights,active:data.active||null,selected:ids.has(data.selected)?data.selected:data.routines[0].id};}
document.getElementById('export').onclick=exportBackup;
document.getElementById('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10_000_000)throw Error('Backup is too large');const restored=validate(JSON.parse(await file.text()));ask('Restore this backup?',`Replace this browser’s records with ${restored.sessions.length} sessions and ${restored.routines.length} routines? Export your current records first if you want to keep them.`,'Restore backup',()=>{state=restored;restEnd=0;save();render();toast('Backup restored.');});}catch(err){toast('This is not a valid GymLog Personal backup.');}e.target.value='';};
window.addEventListener('hashchange',()=>{render();window.scrollTo({top:0});});
window.addEventListener('storage',e=>{if(e.key!==KEY||!e.newValue)return;try{state=validate(JSON.parse(e.newValue));render();toast('Records updated from another tab.');}catch{toast('Could not read changes from another tab.');}});
setInterval(tick,1000);render();if(storageError)toast('Saved data could not be read. Restore a backup or start a new journal.');
